version: '3'
services:
  frontend:
    image: zainebaamir2002/todolist-client:latest
    ports:
      - "3000:3000"
  backend:
    image: zainebaamir2002/todolist-server:latest
    ports:
      - "5500:5500"
    volumes:
      - db-data:/data/db
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
volumes:
  db-data:

